/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface _PrismaMigrations {
  applied_steps_count: Generated<number>;
  checksum: string;
  finished_at: Date | null;
  id: string;
  logs: string | null;
  migration_name: string;
  rolled_back_at: Date | null;
  started_at: Generated<Date>;
}

export interface Hobby {
  id: Generated<number>;
  name: string;
}

export interface Person {
  gender: string;
  id: number;
  job: string;
  name: string;
}

export interface PersonHobby {
  hobbyId: number;
  personId: number;
}

export interface DB {
  _prisma_migrations: _PrismaMigrations;
  Hobby: Hobby;
  Person: Person;
  PersonHobby: PersonHobby;
}
